@TodoApp.Api_HostAddress = http://localhost:5187

POST {{TodoApp.Api_HostAddress}}/api/auth
Accept: application/json
Authorization: Basic test:Welkom01
###

POST {{TodoApp.Api_HostAddress}}/api/auth/logout
Accept: application/json
###

GET {{TodoApp.Api_HostAddress}}/api/users/
Accept: application/json
###

GET {{TodoApp.Api_HostAddress}}/api/users/1
Accept: application/json
###

GET {{TodoApp.Api_HostAddress}}/api/users/current
Accept: application/json
###

POST {{TodoApp.Api_HostAddress}}/api/users/
Accept: application/json
Content-Type: application/json

{
    "Name" : "test99",
    "Email" : "test@test99.dd",
    "Password" : "Welkom01"
}
###

GET {{TodoApp.Api_HostAddress}}/api/todolists
Accept: application/json
###

GET {{TodoApp.Api_HostAddress}}/api/todolists/1
Accept: application/json
###

POST {{TodoApp.Api_HostAddress}}/api/todolists
Accept: application/json
Content-Type: application/json

{
    "Name" : "Test TodoList"
}
###

PUT {{TodoApp.Api_HostAddress}}/api/todolists/1
Accept: application/json
Content-Type: application/json

{   
    "Name" : "Test name changed"
}
###

DELETE {{TodoApp.Api_HostAddress}}/api/todolists/1
Accept: application/json
###

POST {{TodoApp.Api_HostAddress}}/api/todoitems
Accept: application/json
Content-Type: application/json

{   
    "TodoListId" : 3,
    "Title" : "Test by new member!",
    "Status" : 1
}
###

PUT {{TodoApp.Api_HostAddress}}/api/todoitems/3
Accept: application/json
Content-Type: application/json

{   
    "Order" : 99
}
###

Get {{TodoApp.Api_HostAddress}}/api/listmembers/1
Accept: application/json
###

DELETE {{TodoApp.Api_HostAddress}}/api/listmembers/3
Accept: application/json
Content-Type: application/json

{
    "TodoListId" : 3
}
###

POST {{TodoApp.Api_HostAddress}}/api/listmembers
Accept: application/json
Content-Type: application/json

{   
    "UserId" : 2,
    "TodoListId" : 1
}
###


